# Generated by Django 4.2.16 on 2024-11-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='speaker',
        ),
    ]
