# Generated by Django 4.2.16 on 2024-12-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_conversation_speaker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='content',
            new_name='ai_message',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='user',
            new_name='user_message',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='date',
        ),
        migrations.AddField(
            model_name='conversation',
            name='back_messages',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
