# Generated by Django 4.2.16 on 2024-12-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_content_conversation_ai_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountOfMessagesShown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_messages', models.IntegerField(default=5)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='back_messages',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
